resources:
  - name: once-every-5m
    type: time
    source:
      interval: 5m

jobs:
- name: more-show-time
  public: true
  plan:
    - get: once-every-5m
      trigger: true
    - task: show-more-things
      config:
        platform: linux
        inputs:
          - name: once-every-5m
        image_resource:
          type: docker-image
          source:
            repository: alpine
            tag: latest
        run:
          path: sh
          args:
            - -ec
            - |
              sleep 20
              ls -l
