resources:
  - name: once-a-minute
    type: time
    source:
      interval: 5m

jobs:
- name: show-time
  public: true
  plan:
    - get: once-a-minute
      trigger: true
    - task: show-more-things
      config:
        platform: linux
        inputs:
          - name: once-a-minute
        image_resource:
          type: docker-image
          source:
            repository: alpine
            tag: 3.8
        run:
          path: sh
          args:
            - -ec
            - |
              sleep 20
              probe=$RANDOM
              echo "RANDOM: $probe"
              if [ "$probe" -gt "15000" ]; then
                 echo "FAILURE"
                 exit 1
              fi
              ls -l
